### ISSUE TITLE
without with...as..., I get an 

### ISSUE THREAD

**Issue by ZhihaoDU** [funcwj/kaldi-python-io#4]
When use with...as.. statement, the ArchiveWriter works well.

with ArchiveWriter("foo.ark", "foo.scp") as writer:
    for i in range(10):
        mat = np.random.rand(100, 20)
        writer.write("mat-{:d}".format(i), mat)

but, when I don't use with...as... statement, I get an AttributeError
![image](https://user-images.githubusercontent.com/28995683/63206350-450c7980-c0e5-11e9-9461-8ed489e8aa01.png)
If I missed something?

**Comment by funcwj** [comment]
No, it's my implementation's problem. All the subclass of the `Writer` are forced using with `with ... as` statement because the files are initialized in `__enter__` function.

**Comment by funcwj** [comment]
It's an issue and I will fixed it later. Before that you can modify them based on you habits.
